title: VOYAGE
description: 📚 Read book / 💻 Write code / 🔨 Craft shit.

menu:
  Home: /
  About: /about
  Email: mailto:dzmtoast@gmail.com
  Github: https://github.com/toastsgithub

# your name
signoff: ZMou. Duan

# disqus comment thread for post header options ( leave blank if unwanted )
disqus_shortname: 

# set tracking, UA-XXXX-Y
google_analytics: 
